BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[TMP_Logs] (
    [id] NVARCHAR(1000) NOT NULL,
    [logText] VARCHAR(500) NOT NULL,
    [error] BIT NOT NULL CONSTRAINT [TMP_Logs_error_df] DEFAULT 0,
    [createdAt] DATETIME2 NOT NULL,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [TMP_Logs_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
